name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Move dependency files
        run: mv .github/dependency_files/* .

      - name: Install dependencies
        working-directory: /home/runner/work/bulutdersiproje/bulutdersiproje/
        run: npm install

      - name: Run Snyk to check for vulnerabilities
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
